site_name: Mohanson
site_description: Mohanson 的网络日志, 分享数字图像处理, 编译器和虚拟机等领域的原创文章.
site_url: http://accu.cc
site_author: Mohanson
theme:
        name: readthedocs
        highlightjs: true
        custom_dir: custom_theme/
repo_url: https://github.com/mohanson/accu
plugins: []
nav:
- 主页: index.md
- 数字图像处理:
        - 数字图像处理/通道: content/pil/channel.md
        - 数字图像处理/均值: content/pil/mean.md
        - 数字图像处理/对比增强: content/pil/contrast.md
        - 数字图像处理/对比拉伸: content/pil/contrast_tensile.md
        - 数字图像处理/位图切割: content/pil/bit.md
        - 数字图像处理/直方图均衡化: content/pil/histogram_equalization.md
        - 数字图像处理/图像减法: content/pil/sub.md
        - 数字图像处理/加性高斯白噪声与去噪: content/pil/agwn.md
        - 数字图像处理/空间滤波基础: content/pil/spatial_filter.md
        - 数字图像处理/空间滤波/均值滤波: content/pil/spatial_filter_mean.md
        - 数字图像处理/空间滤波/中值滤波: content/pil/spatial_filter_medium.md
        - 数字图像处理/空间滤波/锐化滤波: content/pil/spatial_filter_sharpening.md
        - 数字图像处理/空间滤波/高斯滤波: content/pil/spatial_filter_gaussian_blur.md
        - 数字图像处理/频域滤波基础: content/pil/frequency_filter.md
        - 数字图像处理/频域滤波/低通滤波: content/pil/frequency_filter_lpf.md
        - 数字图像处理/频域滤波/高通滤波: content/pil/frequency_filter_hpf.md
        - 数字图像处理/噪声: content/pil/noise.md
        - 数字图像处理/安全色: content/pil/safe_color.md
        - 数字图像处理/马卡龙色: content/pil/macaron_color.md
        - 数字图像处理/补色和反色: content/pil/complementary_and_invert_color.md
        - 数字图像处理/水印: content/pil/watermark.md
        - 数字图像处理/缩放/最近邻插值法: content/pil/resize_nearst.md
        - 数字图像处理/缩放/最近邻插值法的幽灵事件: content/pil/resize_nearst_ghost.md
        - 数字图像处理/缩放/双线性算法: content/pil/resize_bilinear.md
        - 数字图像处理/缩放/双三次插值法: content/pil/resize_bicubic.md
        - 数字图像处理/字符画: content/pil/ascii.md
        - 数字图像处理/PIL/概览: content/pil/pil_tutorial_overview.md
        - 数字图像处理/PIL/Image: content/pil/pil_image.md
        - 数字图像处理/PIL/ImageChops: content/pil/pil_imagechops.md
        - 数字图像处理/PIL/ImageColor: content/pil/pil_imagecolor.md
        - 数字图像处理/PIL/ImageDraw: content/pil/pil_imagedraw.md
        - 数字图像处理/PIL/ImageEnhance: content/pil/pil_imageenhance.md
        - 数字图像处理/PIL/ImageOps: content/pil/pil_imageops.md
- GameBoy 仿真器:
        - GB/前言: content/gameboy/preface.md
        - GB/虚拟机发展史/硬件仿真器: content/gameboy/history/emulator.md
        - GB/虚拟机发展史/程序虚拟机: content/gameboy/history/runtime.md
        - GB/虚拟机发展史/软件模拟器: content/gameboy/history/simulator.md
        - GB/游戏卡带/漫谈卡带: content/gameboy/cartridge/about_cartridge.md
        - GB/游戏卡带/Header: content/gameboy/cartridge/cartridge_header.md
        - GB/游戏卡带/Memory Bank Controller: content/gameboy/cartridge/memory_bank_controller.md
        - GB/游戏卡带/ROM only: content/gameboy/cartridge/rom_only.md
        - GB/游戏卡带/MBC1: content/gameboy/cartridge/mbc1.md
        - GB/游戏卡带/MBC2: content/gameboy/cartridge/mbc2.md
        - GB/游戏卡带/MBC3: content/gameboy/cartridge/mbc3.md
        - GB/游戏卡带/MBC5: content/gameboy/cartridge/mbc5.md
        - GB/游戏卡带/完整代码: content/gameboy/cartridge/others.md
        - GB/CPU/概览: content/gameboy/cpu/overview.md
        - GB/CPU/算术逻辑单元: content/gameboy/cpu/alu.md
        - GB/CPU/寄存器与存储系统: content/gameboy/cpu/register.md
        - GB/CPU/指令与指令集: content/gameboy/cpu/isa.md
        - GB/CPU/流水线: content/gameboy/cpu/pipeline.md
        - GB/CPU/LR35902 标准指令集: content/gameboy/cpu/lr35902_standard.md
        - GB/CPU/LR35902 扩展指令集: content/gameboy/cpu/lr35902_extension.md
        - GB/CPU/LR35902 时钟周期与频率仿真: content/gameboy/cpu/cycles.md
        - GB/CPU/LR35902 中断: content/gameboy/cpu/interrupts.md
        - GB/CPU/内存管理单元与主板: content/gameboy/cpu/mmu.md
        - GB/视频/概览: content/gameboy/video/overview.md
        - GB/视频/点阵图: content/gameboy/video/dot_matrix.md
        - GB/视频/显示输出: content/gameboy/video/show.md
        - GB/视频/光栅成像原理与概念: content/gameboy/video/crt.md
        - GB/视频/图像显示系统: content/gameboy/video/system.md
        - GB/视频/GPU 寄存器与内存结构: content/gameboy/video/gpu.md
        - GB/视频/代码实现: content/gameboy/video/code.md
        - GB/音频/概览: content/gameboy/audio/overview.md
        - GB/音频/声音的构成: content/gameboy/audio/sound.md
        - GB/音频/Rust Cpal 库介绍: content/gameboy/audio/cpal.md
        - GB/音频/音频系统概念简介: content/gameboy/audio/concept.md
        - GB/音频/寄存器: content/gameboy/audio/register.md
        - GB/音频/512 Hz 时钟信号: content/gameboy/audio/timer.md
        - GB/音频/序列发生器: content/gameboy/audio/frame_sequence.md
        - GB/音频/长度计数器: content/gameboy/audio/length_counter.md
        - GB/音频/音量包络: content/gameboy/audio/vol.md
        - GB/音频/频率扫描器: content/gameboy/audio/frequency_sweep.md
        - GB/音频/方波通道: content/gameboy/audio/square.md
        - GB/音频/可编程波形通道: content/gameboy/audio/wave.md
        - GB/音频/白噪音通道: content/gameboy/audio/noise.md
        - GB/音频/混频器: content/gameboy/audio/mixer.md
        - GB/音频/在计算机上播放: content/gameboy/audio/play.md
        - GB/其它/游戏手柄: content/gameboy/other/joypad.md
        - GB/其它/串行通行接口: content/gameboy/other/serial.md
        - GB/其它/定时器: content/gameboy/other/timer.md
        - GB/其它/硬件初始化工作: content/gameboy/other/init.md
        - GB/其它/测试: content/gameboy/other/test.md
        - GB/后记: content/gameboy/foot.md
- 遗传算法:
        - 遗传算法/简单遗传算法: content/ga/sga.md
        - 遗传算法/格雷码: content/ga/graycode.md
        - 遗传算法/俄罗斯轮盘赌: content/ga/russian_roulette.md
        - 遗传算法/最优保留策略: content/ga/maintain_the_best_solution.md
        - 遗传算法/生物进化模拟: content/ga/evolve.md
        - 遗传算法/愚弄神经网络: content/ga/fooled_nn.md
- Linux x64 汇编:
        - Linux x64 汇编/Hello World: content/linux_x64_asm/linux_x64_part1.md
        - Linux x64 汇编/术语和概念: content/linux_x64_asm/linux_x64_part2.md
        - Linux x64 汇编/栈: content/linux_x64_asm/linux_x64_part3.md
        - Linux x64 汇编/宏: content/linux_x64_asm/linux_x64_part4.md
        - Linux x64 汇编/AT&T: content/linux_x64_asm/linux_x64_part5.md
        - Linux x64 汇编/汇编与 C: content/linux_x64_asm/linux_x64_part6.md
- JIT 编译器原理简述:
        - JIT 编译器原理简述/原理简述: content/jit_tour/principle.md
        - JIT 编译器原理简述/实现 Brainfuck 解释器与 IR 优化: content/jit_tour/brainfuck_interpreter.md
        - JIT 编译器原理简述/实现 Brainfuck JIT 编译器: content/jit_tour/brainfuck_jit.md
- Cryptography:
        - Cryptography/群环域: content/cryptography/group_ring_field.md
        - Cryptography/椭圆曲线: content/cryptography/ecc.md
        - Cryptography/椭圆曲线签名与验签: content/cryptography/ecdsa.md
        - Cryptography/椭圆曲线签名的错误用法: content/cryptography/ecdsa_ps3_hack.md
        - Cryptography/椭圆曲线空间扩展之 Jacobian: content/cryptography/ecc_jacobian.md
        - Cryptography/椭圆曲线双线性配对: content/cryptography/ecc_pairing.md
        - Cryptography/多项式运算: content/cryptography/polynomial_math.md
        - Cryptography/KZG 多项式承诺: content/cryptography/kzg.md
        - Cryptography/蒙哥马利约分算法: content/cryptography/montgomery.md
        - Cryptography/默克尔树: content/cryptography/merkle_tree.md
        - Cryptography/抗量子 Lamport 签名: content/cryptography/lamport.md
        - Cryptography/抗量子 W-OTS 签名: content/cryptography/winternitz.md
        - Cryptography/RC4: content/cryptography/rc4.md
        - Cryptography/谷歌两步验证算法实现: content/cryptography/2fa.md
- 人工智能:
        - 人工智能/图像风格转移: content/ai/neural_style_transfer.md
        - 人工智能/Dlib 人脸识别: content/ai/dlib.md
- CKB:
        - CKB/Neuron 钱包: content/ckb/neuron.md
        - CKB/开发网络: content/ckb/dev.md
- Python:
        - Python/f-strings: content/python/f_strings.md
        - Python/Windows 编程: content/python/windows.md
        - Python/Pypi: content/python/pypi.md
        - Python/Matplotlib: content/python/matplotlib.md
- Go:
        - Go/按行读取文件: content/go/read_line.md
        - Go/Socket 编程: content/go/socket.md
        - Go/Socket 假如服务端不调用 Accept: content/go/socket_not_accept.md
        - Go/TLS: content/go/tls.md
        - Go/目录监听: content/go/fswatch.md
        - Go/Cgo: content/go/cgo.md
        - Go/令牌桶算法限流: content/go/token_bucket.md
- Rust 速成课:
        - Rust 速成课/概览: content/rust_crash/overview.md
        - Rust 速成课/开发环境搭建: content/rust_crash/env.md
        - Rust 速成课/变量与可变性: content/rust_crash/variables_and_mutability.md
        - Rust 速成课/数据类型: content/rust_crash/data_type.md
        - Rust 速成课/流程控制: content/rust_crash/control_flow.md
        - Rust 速成课/结构体, 函数与方法: content/rust_crash/structs.md
        - Rust 速成课/泛型类型: content/rust_crash/trait.md
        - Rust 速成课/所有权: content/rust_crash/ownership.md
        - Rust 速成课/引用与借用: content/rust_crash/borrow.md
        - Rust 速成课/二叉树: content/rust_crash/binary_tree.md
- 圣杯:
        - 圣杯/追寻之路: content/sangreal/overview.md
        - 圣杯/网格交易: content/sangreal/grid.md
        - 圣杯/马丁格尔爆仓之路: content/sangreal/martingale.md
        - 圣杯/双均线策略: content/sangreal/sma.md
        - 圣杯/阻力支撑相对强度指标: content/sangreal/rsrs.md
- AHK:
        - AHK/安装和使用: content/ahk/overview.md
        - AHK/在一个热键上开启或关闭: content/ahk/toggle.md
- 演讲:
        - 演讲/minits 以 LLVM 为后端的 TypeScript 静态编译器: content/speech/minits.md
        - 演讲/WASC WebAssembly 到 RISC-V 的 AOT 编译器(中文): content/speech/wasc_cn.md
        - 演讲/WASC WebAssembly 到 RISC-V 的 AOT 编译器(英文): content/speech/wasc_en.md
        - 演讲/CKB VM B 扩展指令集与宏指令融合: content/speech/ckb_vm_b_extension_and_mop.md
        - 演讲/RISC-V 在区块链智能及云原生中的应用, 机遇与挑战: content/speech/riscv_in_blockchain.md
        - 演讲/我们如何通过模糊测试保证 CKB VM 的正确性(中文): content/speech/ckb_vm_fuzzing_cn.md
        - 演讲/我们如何通过模糊测试保证 CKB VM 的正确性(英文): content/speech/ckb_vm_fuzzing_en.md
        - 演讲/我们如何通过手工汇编代码击败 Rust 的零成本抽象: content/speech/zero_cost_abstractions.md
        - 演讲/EVM 简介: content/speech/evm.md
- 杂项:
        - 杂项/生命游戏: content/misc/game_of_life/overview.md
        - 杂项/算法心得笔记: content/misc/hackers_delight.md
        - 杂项/霍夫曼编码: content/misc/huffman.md
        - 杂项/时间的终结: content/misc/end_of_time.md
        - 杂项/RISC-V 工具链: content/misc/riscv_toolchains.md
        - 杂项/常用数学符号输入: content/misc/mathematics_symbol.md
        - 杂项/神的存在性证明: content/misc/proof_of_god_existence.md
- 竹书纪年:
        - Y2019: content/diary/2019.md
        - Y2020: content/diary/2020.md
        - Y2021: content/diary/2021.md
        - Y2022: content/diary/2022.md
        - Y2023: content/diary/2023.md
